databases:
  - name: flexam-db
    databaseName: flexam
    user: flexam_user
    plan: free

services:
  - type: web
    name: flexam-web
    env: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn -c gunicorn_config.py run:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flexam-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: flexam-redis
          property: connectionString
      - key: SECRET_KEY
        generate: true
      - key: STORAGE_TYPE
        value: local

  - type: redis
    name: flexam-redis
    plan: free
