"""add entity_awareness_to_component_definition

Revision ID: 5a08f47834d9
Revises: 660cf5678fa4
Create Date: 2026-07-28 15:35:54.203754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a08f47834d9'
down_revision = '660cf5678fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('field_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_foreign_key(None, 'entity_definitions', ['entity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_definitions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('field_ids')
        batch_op.drop_column('entity_id')

    # ### end Alembic commands ###
