"""add notifications table

Revision ID: 622b26f9fb5e
Revises: ef181466c889
Create Date: 2026-07-26 11:50:22.638075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622b26f9fb5e'
down_revision = 'ef181466c889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    # ### end Alembic commands ###
