"""add_component_registry_table

Revision ID: 660cf5678fa4
Revises: 87777fce11b1
Create Date: 2026-07-28 11:28:23.235275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '660cf5678fa4'
down_revision = '87777fce11b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_type', sa.String(length=64), nullable=False),
    sa.Column('property_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ui_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_registry')
    # ### end Alembic commands ###
