"""add event_metadata to integrity log

Revision ID: 94135f5a9d9f
Revises: 45645a458d64
Create Date: 2026-07-28 16:59:28.272387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94135f5a9d9f'
down_revision = '45645a458d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrity_logs', schema=None) as batch_op:
        batch_op.drop_column('event_metadata')

    # ### end Alembic commands ###
