"""add sequence_states table

Revision ID: 9c5b25527903
Revises: 622b26f9fb5e
Create Date: 2026-07-26 23:04:17.253678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5b25527903'
down_revision = '622b26f9fb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_definition_id', sa.UUID(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_definition_id'], ['entity_definitions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_definition_id', name='_tenant_entity_sequence_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequence_states')
    # ### end Alembic commands ###
