"""add allowed_response_modes to AssessmentComponent

Revision ID: b698ba2a9f89
Revises: c7e5b574d1f7
Create Date: 2026-07-27 13:24:13.895901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b698ba2a9f89'
down_revision = 'c7e5b574d1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_response_modes', sa.ARRAY(sa.String(length=32)), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_components', schema=None) as batch_op:
        batch_op.drop_column('allowed_response_modes')

    # ### end Alembic commands ###
