"""add ui_config and position to FieldDefinition

Revision ID: b7ae0fb276ca
Revises: 5bd70e57a1e2
Create Date: 2026-07-25 09:29:17.684217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7ae0fb276ca'
down_revision = '5bd70e57a1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ui_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
        batch_op.drop_column('order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('position')
        batch_op.drop_column('ui_config')

    # ### end Alembic commands ###
