"""add dynamic UI tables

Revision ID: d3290dc4ff9b
Revises: 9c5b25527903
Create Date: 2026-07-27 10:27:09.368643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3290dc4ff9b'
down_revision = '9c5b25527903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('component_type', sa.String(length=32), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='_tenant_page_slug_uc')
    )
    with op.batch_alter_table('page_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_definitions_slug'), ['slug'], unique=False)

    op.create_table('layout_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component_definitions.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page_definitions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layout_definitions')
    with op.batch_alter_table('page_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_definitions_slug'))

    op.drop_table('page_definitions')
    op.drop_table('component_definitions')
    # ### end Alembic commands ###
