"""add enforced_question_type to assessment_components

Revision ID: ef181466c889
Revises: f1fb4f866c08
Create Date: 2026-07-25 22:48:45.166128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef181466c889'
down_revision = 'f1fb4f866c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enforced_question_type', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_components', schema=None) as batch_op:
        batch_op.drop_column('enforced_question_type')

    # ### end Alembic commands ###
